### ISSUE TITLE
vivos pipe

### ISSUE THREAD

**Issue by drernie** [data-yaml/vivos#30]
= Smart handler

1. Tells stack which `foo.pipe.json` triggers it (or yaml)
2. Stack removes foo.pipe.md
3. Checks for 'foo.pipe.md'. Does not run if present. Creates it afterwards.

**Comment by drernie** [comment]
Next Steps

- add object_path to Vivos
- add 'save' to UPath
- write file.md with 'run' output
- test "newer"
- integration test manually

**Comment by drernie** [comment]
- call router on every PUT
- upload new test.pipe.json? (cf. Auto-Analyze)

**Comment by drernie** [comment]
Access Defined to source bucket
Need to (somehow) re-add Lambda permissions to all buckets?
```
2024-01-06T22:43:02.523Z	863ae199-8544-4f74-acf9-452b8381e1d2	ERROR	Invoke Error 	{"errorType":"AccessDenied","errorMessage":"Access Denied","name":"AccessDenied","$fault":"client","$metadata":{"httpStatusCode":403,"requestId":"0DFM3T1RZ49RSZEG","extendedRequestId":"ZxfmDptIh/P3CrLWp0hEKnHDSTS39osmKPX0egUgy5nqtMtCOqyXbzTomL8u3wsR5YuEjRPTcNY=","attempts":1,"totalRetryDelay":0},"Code":"AccessDenied","RequestId":"0DFM3T1RZ49RSZEG","HostId":"ZxfmDptIh/P3CrLWp0hEKnHDSTS39osmKPX0egUgy5nqtMtCOqyXbzTomL8u3wsR5YuEjRPTcNY=","message":"Access Denied","stack":["AccessDenied: Access Denied","    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)","    at /var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:18:39","    at de_GetObjectAttributesCommandError (/var/runtime/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4425:20)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24","    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20","    at async /var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46","    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26","    at async _UPath.getAttributesS3 (/var/task/index.js:29814:22)","    at async _Pipe.sentinel_newer (/var/task/index.js:30033:27)"]}
```

**Comment by drernie** [comment]
```
  "vivoslambdaamazonawscomroleDefaultPolicyE0A5E1D8": {
   "Type": "AWS::IAM::Policy",
   "Properties": {
    "PolicyDocument": {
     "Statement": [
      {
       "Action": "sns:Publish",
       "Effect": "Allow",
       "Resource": {
        "Ref": "VivosStatusTopicA15DB4F3"
       },
       "Sid": "VivosLambdaSNSPolicy"
      },
      {
       "Action": [
        "s3:ListBucket",
        "s3:GetObject",
        "s3:PutObject",
        "SNS:Publish"
       ],
       "Effect": "Allow",
       "Resource": [
        {
         "Fn::Join": [
          "",
          [
           "arn:aws:s3:::",
           {
            "Ref": "status13EA9EF7"
           }
          ]
         ]
        },
        {
         "Fn::Join": [
          "",
          [
           "arn:aws:s3:::",
           {
            "Ref": "status13EA9EF7"
           },
           "/*"
          ]
         ]
        }
       ],
       "Sid": "VivosLambdaS3Policy"
      }
     ],
     "Version": "2012-10-17"
    },
```
Only one bucket? And is it effective? Why did the write fail?

**Comment by drernie** [comment]
Now runs, but only on pipe-stack-status.

**Comment by drernie** [comment]
Success -- but only when using the CDK-creatd 'vivo-pipes' bucket.
